# Generated by Django 3.2.2 on 2021-05-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_top_three',
            field=models.BooleanField(default=False),
        ),
    ]
