# Generated by Django 3.2.2 on 2021-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_is_top_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='sold_houses',
            field=models.IntegerField(default=0),
        ),
    ]
